apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
spec:
  restartPolicy: Never
  containers:
  - name: helloworld
    image: {{ .Values.image.repository }}:{{ default "latest" .Values.image.tag }}
