name: Build and Push
on:
  push:
    branches: 
      - main
    paths:
      - 'myapp/src/**'

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # outputs:
    #   image_tag: ${{ steps.version.outputs.version }}
    steps:
      # - uses: actions/checkout@v4

      - name: Build Docker image and push to Amazon ECR
        run: |
          mvn --version
          docker --version
          blabla
          echo blibli
